### ISSUE TITLE
Report an error when I run the command: python scripts/nullrecurrent_inference.py -d deg_Mg_pH10 -i example.txt -o predict.txt

### ISSUE THREAD

**Issue by Jojo-LIU-LIU** [eternagame/KaggleOpenVaccine#3]
### Expected Behavior

Hi, I am trying the model Nurrrecurrent. I followed the corresponding instructions to build the environment or dependency. However the command "python scripts/nullrecurrent_inference.py -d deg_Mg_pH10 -i example.txt -o predict.txt " could not be executed sucessfully. Look forward replys. Thanks!

### Current Behavior

Report an error:
['CGC']
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 1391.61it/s]
Traceback (most recent call last):
  File "/home/ljj/001.archive/KaggleOpenVaccine-main/scripts/nullrecurrent_inference.py", line 1027, in <module>
    main(sys.argv[1:])
  File "/home/ljj/001.archive/KaggleOpenVaccine-main/scripts/nullrecurrent_inference.py", line 1012, in main
    all_preds = df.progress_apply(lambda row: _make_pred(row['sequence'], output_feature), axis=1)
  File "/home/ljj/miniconda3/lib/python3.9/site-packages/tqdm/std.py", line 805, in inner
    return getattr(df, df_function)(wrapper, **kwargs)
  File "/home/ljj/miniconda3/lib/python3.9/site-packages/pandas/core/frame.py", line 9568, in apply
    return op.apply().__finalize__(self, method="apply")
  File "/home/ljj/miniconda3/lib/python3.9/site-packages/pandas/core/apply.py", line 764, in apply
    return self.apply_standard()
  File "/home/ljj/miniconda3/lib/python3.9/site-packages/pandas/core/apply.py", line 891, in apply_standard
    results, res_index = self.apply_series_generator()
  File "/home/ljj/miniconda3/lib/python3.9/site-packages/pandas/core/apply.py", line 907, in apply_series_generator
    results[i] = self.f(v)
  File "/home/ljj/miniconda3/lib/python3.9/site-packages/tqdm/std.py", line 800, in wrapper
    return func(*args, **kwargs)
  File "/home/ljj/001.archive/KaggleOpenVaccine-main/scripts/nullrecurrent_inference.py", line 1012, in <lambda>
    all_preds = df.progress_apply(lambda row: _make_pred(row['sequence'], output_feature), axis=1)
  File "/home/ljj/001.archive/KaggleOpenVaccine-main/scripts/nullrecurrent_inference.py", line 943, in _make_pred
    mfe_structure = mfe(sequence, package='eternafold')
  File "/home/ljj/001.archive/arnie/mfe.py", line 109, in mfe
    struct = mfe_contrafold_(seq, version=version, T=T, constraint=constraint, DIRLOC=package_locs['eternafold'],
  File "/home/ljj/001.archive/arnie/mfe.py", line 344, in mfe_contrafold_
    fname = '%s.in' % filename()
  File "/home/ljj/001.archive/arnie/utils.py", line 569, in filename
    tmpdir = load_package_locations()['TMP']
KeyError: 'TMP'

![image](https://user-images.githubusercontent.com/113112908/231372038-7b5bac53-f01a-4de1-a282-fcfe59190d89.png)

### Reproduction Steps

1, git-clone KaggleOpenVaccine repo
2, conda install --file requirements.txt.
3, Install EternaFold (the nullrecurrent model uses this), available for free noncommercial use [here](https://www.eternagame.org/about/software).

4, Install ViennaRNA (the DegScore-XGBoost model uses this), available [here](https://www.tbi.univie.ac.at/RNA/).

5, Git clone [Arnie](https://github.com/DasLab/arnie), which wraps EternaFold in python and allows RNA thermodynamic calculations across many packages. Follow instructions [here](https://github.com/DasLab/arnie/blob/master/docs/setup_doc.md) to link EternaFold to it.

6, Add path to this repository as KOV_PATH (so that script can find path to stored model files):

    export KOV_PATH='/path/to/KaggleOpenVaccine'
7, To run the nullrecurrent winning solution on one construct, given in example.txt:
    CGC
   Run: python scripts/nullrecurrent_inference.py -d deg_Mg_pH10  -i example.txt -o predict.txt
Report an error:

**Comment by lili19911005** [comment]
I also encountered the same problem. Have you solved it?

**Comment by HWaymentSteele** [comment]
Hi @lili19911005 and @Jojo-LIU-LIU , can you provide the error message you're getting?
